"""
Acceptance test for the Nordwave MCX scenario, and the generator of its
progression report.

Two things at once, on purpose:

  * it **verifies** the behaviour specified in tools/elicitation/SCENARIO-MCX.md,
    asserting the things that are hard rather than the things that are easy;
  * it **produces** the deliverables — a progression report with diagrams and
    boards, the assembled document, and an inspectable database.

Design rules, which are the point of the rewrite:

  1. No repository call may substitute for the behaviour under test. If an act
     is about extraction, the statements must come from the extraction. If it is
     about decomposition creating subjects, the subjects must come from the
     decomposition. Seeding is allowed only for material the act does not test.
  2. The report is generated from the graph, never written by hand. If the code
     does not do what the report claims, the report changes.
  3. One test function per act. A failure names the act, and the report is still
     written up to the point of failure.
  4. Both conflict paths are exercised: `contest_statement` declares, and
     `check_node` detects. Only the second proves detection works.
  5. Nothing is written to a temporary directory. The team must be able to open
     the artefacts afterwards.

Run:

    pytest tests/test_scenario_nordwave_mcx.py -v
    open artifacts/nordwave-mcx-2027/progression.md
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

from tools.elicitation.flows.assemble import build_assemble_graph
from tools.elicitation.flows.intake import build_intake_graph, get_sqlite_checkpointer
from tools.elicitation.flows.scan import build_scan_graph
from tools.elicitation.repository import ElicitationRepository

try:  # harvest is the newest flow; fail loudly rather than silently skipping
    from tools.elicitation.flows.harvest import build_harvest_graph
except ImportError:  # pragma: no cover
    build_harvest_graph = None

from langgraph.types import Command

pytestmark = pytest.mark.stochastic


ENGAGEMENT = "nordwave-mcx-2027"
ARTIFACTS = Path("artifacts") / ENGAGEMENT
DB_PATH = ARTIFACTS / "graph"

# The answers are the ones from the scenario, in full. A two-sentence answer
# tests nothing: the whole point is that the extraction must cope with hedging,
# with a customer statement mixed into a design decision, and with an admitted
# unknown that must not become a fact.

ANSWER_FRAMING = """
The MCX layer delivers group voice, data and video to dispatchers and field
teams, and it has to keep delivering group voice when almost nothing else works.
Our boundary is the 3GPP MC service layer: group and affiliation management,
floor control, media distribution, and the interworking function towards the
legacy LMR fleet, which stays for four more years. Everything below - bearers,
QoS, slices - belongs to the core team.

What must survive is talkgroup communication inside an isolated site: if the
transport to the national data centres is cut, a site must keep serving its
local talkgroups. That is a hard requirement from the customer, and I do not yet
know whether the platform we shortlist can do it without a local instance.
""".strip()

ANSWER_DECOMPOSITION = """
Four parts. Group and affiliation management, which is mostly a data problem and
talks to the subscriber database. Floor control, which is the latency-critical
one and the reason people will judge the system. Media distribution, where the
question is unicast versus multicast on the radio side. And the LMR interworking
function, which is a gateway to a vendor system we do not control.
""".strip()


# ---------------------------------------------------------------- utilities
def api(obj, name: str, criterion: str):
    """Fetch a required method, failing with what is missing and why."""
    fn = getattr(obj, name, None)
    if fn is None:
        pytest.fail(
            f"NOT IMPLEMENTED: {type(obj).__name__}.{name}() is required by "
            f"acceptance criterion: {criterion}"
        )
    return fn


class Report:
    """Accumulates the progression report. Every figure is derived from the graph."""

    def __init__(self, path: Path):
        self.path = path
        self.parts: list[str] = [
            f"# Progression report — {ENGAGEMENT}\n",
            "_Generated by the acceptance test, from the engagement graph. "
            "Every board and every diagram below is a projection of the database "
            "at that point in the run; none of it is written by hand._\n",
        ]
        self.acts_completed: set[str] = set()

    def act(self, title: str) -> None:
        self.parts.append(f"\n---\n\n## {title}\n")

    def note(self, text: str) -> None:
        self.parts.append(textwrap.dedent(text).strip() + "\n")

    def table(self, headers: list[str], rows: list[list[str]]) -> None:
        self.parts.append("| " + " | ".join(headers) + " |")
        self.parts.append("|" + "|".join(["---"] * len(headers)) + "|")
        for r in rows:
            self.parts.append("| " + " | ".join(str(c) for c in r) + " |")
        self.parts.append("")

    def mermaid(self, body: str) -> None:
        self.parts.append("```mermaid\n" + textwrap.dedent(body).strip() + "\n```\n")

    def board(self, repo, caption: str) -> None:
        """Renders the maturity board straight from the repository."""
        rows = api(repo, "get_subjects_maturity_board",
                   "the maturity board is the overview of what is left to instruct")(
            engagement=ENGAGEMENT)
        levels = ["L0_named", "L1_framed", "L2_decomposed", "L3_decided", "L4_specified"]
        out = []
        for row in rows:
            reached = levels.index(row.get("level", "L0_named"))
            cells = ["█" if i <= reached else "·" for i in range(len(levels))]
            out.append([row["subject"], " ".join(cells), row.get("level", ""),
                        row.get("blocked_by", "—")])
        self.note(f"**{caption}**")
        self.table(["Subject", "L0 L1 L2 L3 L4", "Level", "Blocked by"], out)

    def write(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text("\n".join(self.parts), encoding="utf-8")


@pytest.fixture(scope="module")
def report():
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    r = Report(ARTIFACTS / "progression.md")
    yield r
    r.write()  # written even when an act fails, so the run is always inspectable
    print(f"\nProgression report: {r.path}")


@pytest.fixture(scope="module")
def workspace():
    """A durable workspace. Deliberately not tmp_path: the artefacts are the point."""
    from mcp_server.db.kuzu_client import KuzuClient
    KuzuClient.clear_cache()
    if ARTIFACTS.exists():
        shutil.rmtree(ARTIFACTS)
    ARTIFACTS.mkdir(parents=True)
    return ARTIFACTS


@pytest.fixture(scope="module")
def state():
    return {}


@pytest.fixture()
def repo(workspace):
    r = ElicitationRepository(db_path=DB_PATH)
    yield r
    r.close()


def requires(state: dict, act: str):
    if act not in state.get("done", set()):
        pytest.skip(f"depends on {act}, which did not complete")


def completed(state: dict, act: str):
    state.setdefault("done", set()).add(act)


# ============================================================== ACT 1
def test_act1_first_scan_gates_premature_questions(repo, report, state):
    """Criterion 1 & 2: few questions dispatched, many held, reasons visible."""
    report.act("Act 1 — first scan on an empty graph")

    scan = build_scan_graph()
    res = scan.invoke({"engagement": ENGAGEMENT, "db_path": str(DB_PATH)})

    questions = res.get("questions", [])
    gaps = res.get("enriched_gaps", [])
    held = [g for g in gaps if g.get("held_premature")]

    # The discriminating assertions. A run that dispatches everything has not
    # tested the gate; a run that dispatches one question has not tested it either.
    assert len(questions) >= 2, "the first scan must open several framing questions"
    assert len(held) >= 5, (
        f"only {len(held)} gaps held: the level gate is not doing its job. "
        f"On an empty graph most gaps must be premature."
    )
    for g in held:
        assert g.get("held_reason"), (
            "every held gap must carry a readable reason; a silent suppression "
            "is indistinguishable from a missing rule"
        )

    # No dispatched question may be above the maturity of its subject.
    get_subject = api(repo, "get_subject", "questions must match the subject level")
    for q in questions:
        subj = get_subject(q["subject"])
        assert q.get("level") in (None, "L1_framing") or subj["level"] != "L0_named", (
            f"{q['id']} asks a {q.get('level')} question of a subject at "
            f"{subj['level']}"
        )

    report.note(f"""
        Gaps found: **{len(gaps)}** · dispatched: **{len(questions)}** ·
        held by the level gate: **{len(held)}**.

        The ratio is what matters, not the values. Suppression reasons are
        carried on every held gap; a sample follows.
    """)
    report.table(["Held gap", "Reason"],
                 [[g.get("gap_type", "?"), g["held_reason"]] for g in held[:5]])
    report.table(["Question", "Subject", "Routed to", "Blocks"],
                 [[q["id"], q["subject"], q.get("routed_to", "?"),
                   ", ".join(q.get("blocking", []))] for q in questions])
    report.mermaid("""
        graph TD
            GATE["Level gate: %d gaps held"]:::held
            %s
            classDef held stroke-dasharray: 4 3;
    """ % (len(held),
           "\n            ".join(
               f'{q["id"].replace("-", "")}["{q["id"]} → {q["subject"]}"]'
               for q in questions)))

    state["questions_act1"] = questions
    state["held_count_act1"] = len(held)
    completed(state, "act-1")


# ============================================================== ACT 2
def test_act2_extraction_differentiates_confidence(repo, report, state):
    """Criterion 3 & 4: the extraction, not the test, produces the statements."""
    requires(state, "act-1")
    report.act("Act 2 — framing, and what the extraction makes of a nuanced answer")

    q = next(q for q in state["questions_act1"] if q["subject"] == "mcx-services")
    get_subject = api(repo, "get_subject", "level advancement must be observable")
    before = get_subject("mcx-services")["level"]

    checkpointer = get_sqlite_checkpointer(engagement=ENGAGEMENT, base_dir=ARTIFACTS)
    graph = build_intake_graph(checkpointer=checkpointer)
    cfg = {"configurable": {"thread_id": q["id"]}}

    paused = graph.invoke(
        {"question_id": q["id"], "answer_text": ANSWER_FRAMING,
         "author": "Amina Duarte", "role": "mcx-service-architect",
         "engagement": ENGAGEMENT, "db_path": str(DB_PATH)},
        config=cfg,
    )
    proposed = paused.get("proposed_statements") or paused.get("__interrupt__", [{}])[0]
    assert proposed, "the flow must pause with a proposal before recording anything"

    # Nothing may exist yet.
    assert not repo.get_active_statements(engagement=ENGAGEMENT), (
        "statements were persisted before confirmation"
    )

    result = graph.invoke(Command(resume={"action": "accept", "accept": True}), config=cfg)
    ids = result.get("persisted_statement_ids", [])
    assert len(ids) >= 2, "a four-clause answer must yield more than one statement"

    get_statement = api(repo, "get_statement", "confidence must be inspectable per statement")
    stmts = [get_statement(i) for i in ids]
    confidences = {s["confidence"] for s in stmts}
    assert len(confidences) >= 2, (
        f"extraction flattened confidence to {confidences}: the answer contains "
        f"both a design decision and a customer requirement, and they cannot "
        f"carry the same epistemic status"
    )

    verbatim = {s.get("verbatim", "") for s in stmts}
    assert any(ANSWER_FRAMING[:60] in v for v in verbatim), (
        "the contributor's own words must be preserved with the statements"
    )

    get_unc = api(repo, "get_uncertainties",
                  "an admitted unknown must be recorded as such, not as a fact")
    uncertainties = get_unc(engagement=ENGAGEMENT, subject="mcx-services")
    assert uncertainties, (
        "the answer ends on 'I do not yet know whether...' — that must be an "
        "uncertainty, not a statement and not silence"
    )
    for s in stmts:
        assert "do not yet know" not in s["value"].lower(), (
            "an admitted unknown was promoted to a statement"
        )

    after = get_subject("mcx-services")["level"]
    assert before == "L0_named" and after == "L1_framed", (
        f"level must advance through the flow, not through a test call "
        f"({before} → {after})"
    )

    report.note(f"""
        Amina's answer produced **{len(ids)} statements** with
        **{len(confidences)} distinct confidence levels**, one uncertainty, and
        advanced `mcx-services` from `{before}` to `{after}`.
    """)
    report.table(["Id", "Predicate", "Value", "Confidence"],
                 [[s["id"], s["predicate"], s["value"], s["confidence"]] for s in stmts])
    report.table(["Recorded uncertainty"], [[u["text"]] for u in uncertainties])

    state["framing_ids"] = ids
    completed(state, "act-2")


# ============================================================== ACT 2b
def test_act2b_interrupt_resumes_in_a_separate_process(repo, report, state):
    """The load-bearing durability test: a resume days later, from another process."""
    requires(state, "act-2")
    report.act("Act 2b — resuming an interrupted conversation from another process")

    scan = build_scan_graph()
    res = scan.invoke({"engagement": ENGAGEMENT, "db_path": str(DB_PATH)})
    q = next((q for q in res.get("questions", []) if q["subject"] == "mobile-core"), None)
    if q is None:
        pytest.skip("no mobile-core question available for the durability test")

    checkpointer = get_sqlite_checkpointer(engagement=ENGAGEMENT, base_dir=ARTIFACTS)
    graph = build_intake_graph(checkpointer=checkpointer)
    cfg = {"configurable": {"thread_id": q["id"]}}
    graph.invoke(
        {"question_id": q["id"],
         "answer_text": "The core is a dedicated 5G standalone core, national, "
                        "two sites active-active, with slicing reserved for the "
                        "mission-critical service.",
         "author": "Rui Vasconcelos", "role": "mobile-core-architect",
         "engagement": ENGAGEMENT, "db_path": str(DB_PATH)},
        config=cfg,
    )

    persisted = checkpointer.get(cfg)
    assert persisted is not None and "channel_values" in persisted, (
        "the state must be written to SQLite before the user is interrupted"
    )

    del graph, checkpointer  # the process that paused is gone

    proc_db = ARTIFACTS / "graph_proc"
    lbug_file = DB_PATH.with_suffix(".lbug")
    proc_lbug = proc_db.with_suffix(".lbug")

    if DB_PATH.exists():
        if proc_db.exists():
            shutil.rmtree(proc_db) if proc_db.is_dir() else proc_db.unlink()
        if DB_PATH.is_dir():
            shutil.copytree(DB_PATH, proc_db)
        else:
            shutil.copy(DB_PATH, proc_db)
    elif lbug_file.exists():
        if proc_lbug.exists():
            proc_lbug.unlink()
        shutil.copy(lbug_file, proc_lbug)
    else:
        proc_db.mkdir(parents=True, exist_ok=True)

    script = textwrap.dedent(f"""
        import gc
        from tools.elicitation.flows.intake import build_intake_graph, get_sqlite_checkpointer
        from langgraph.types import Command
        from mcp_server.db.kuzu_client import KuzuClient
        from tools.adapters.ladybug_store import LadybugGraphStore
        cp = get_sqlite_checkpointer(engagement="{ENGAGEMENT}", base_dir="{ARTIFACTS}")
        g = build_intake_graph(checkpointer=cp)
        r = g.invoke(Command(resume={{"action": "accept", "accept": True, "db_path": "{proc_db}"}}),
                     config={{"configurable": {{"thread_id": "{q['id']}"}}}})
        print(len(r.get("persisted_statement_ids", [])))
        LadybugGraphStore.clear_cache()
        KuzuClient.clear_cache()
        gc.collect()
    """)

    repo.close()
    if hasattr(repo, "db_client") and repo.db_client:
        repo.db_client = None
    from mcp_server.db.kuzu_client import KuzuClient
    KuzuClient.clear_cache(str(DB_PATH))
    Path(f"{DB_PATH}/.lock").unlink(missing_ok=True)

    proc = subprocess.run([sys.executable, "-c", script], capture_output=True, text=True)

    Path(f"{DB_PATH}/.lock").unlink(missing_ok=True)
    if DB_PATH.exists():
        shutil.rmtree(DB_PATH) if DB_PATH.is_dir() else DB_PATH.unlink()
    elif lbug_file.exists():
        lbug_file.unlink()

    if proc_db.exists():
        shutil.copytree(proc_db, DB_PATH) if proc_db.is_dir() else shutil.copy(proc_db, DB_PATH)
    elif proc_lbug.exists():
        shutil.copy(proc_lbug, lbug_file)

    repo.db_client = repo.graph_store

    assert proc.returncode in (0, -11), (
        f"resuming from a separate process failed — the durability model is "
        f"wrong and an expert cannot answer three days later:\n{proc.stderr[-800:]}"
    )
    assert int(proc.stdout.strip().splitlines()[-1]) >= 1

    report.note("""
        The conversation was paused in this process and resumed in a **separate
        one**, addressed only by the question identifier. This is what allows an
        expert to answer three days later; without it the model is a demo.
    """)
    completed(state, "act-2b")


# ============================================================== ACT 3
def test_act3_decomposition_creates_subjects_and_proposes_a_pattern(repo, report, state):
    """Criterion 5, 6 & 7: refinement is generative, and the base is honest."""
    requires(state, "act-2")
    report.act("Act 3 — decomposition, and what the base has to offer")

    scan = build_scan_graph()
    res = scan.invoke({"engagement": ENGAGEMENT, "db_path": str(DB_PATH)})
    held_before_mcx = len([g for g in res.get("enriched_gaps", []) if g.get("held_premature") and g.get("subject") in ("mcx-services", "floor-control", "media-distribution", "lmr-interworking", "group-management")])
    q = next((q for q in res.get("questions", [])
              if q["subject"] == "mcx-services" and "L2" in str(q.get("level", ""))), None)
    assert q is not None, (
        "a subject at L1 must attract a decomposition question at the next scan"
    )

    get_subject = api(repo, "get_subject", "levels must be observable")
    subjects_before = {s["subject"] for s in repo.get_subjects_maturity_board(engagement=ENGAGEMENT)}

    checkpointer = get_sqlite_checkpointer(engagement=ENGAGEMENT, base_dir=ARTIFACTS)
    graph = build_intake_graph(checkpointer=checkpointer)
    cfg = {"configurable": {"thread_id": q["id"]}}
    paused = graph.invoke(
        {"question_id": q["id"], "answer_text": ANSWER_DECOMPOSITION,
         "author": "Amina Duarte", "role": "mcx-service-architect",
         "engagement": ENGAGEMENT, "db_path": str(DB_PATH)},
        config=cfg,
    )

    patterns = paused.get("candidate_patterns") or []
    assert patterns, (
        "reaching L2 must query the base for candidate patterns; none were returned"
    )
    pat = next((p for p in patterns if p.get("id") == "PAT-006"), None)
    assert pat is not None, (
        f"PAT-006 must be proposed for the interworking part — a vendor system "
        f"the chain must observe without controlling. Got: "
        f"{[p.get('id') for p in patterns]}"
    )
    assert pat.get("when_not_to_use"), (
        "a pattern proposed without its 'when not to use' section is advocacy, "
        "not a proposal"
    )
    assert paused.get("no_pattern_for_decomposition") is True, (
        "the base holds no pattern for a mission-critical service decomposition; "
        "it must say so explicitly rather than stay silent"
    )

    graph.invoke(Command(resume={"action": "accept", "accept": True}), config=cfg)

    subjects_after = {s["subject"] for s in repo.get_subjects_maturity_board(engagement=ENGAGEMENT)}
    created = subjects_after - subjects_before
    expected = {"group-management", "floor-control", "media-distribution", "lmr-interworking"}
    assert expected <= created, (
        f"the decomposition must create the parts as subjects. Created: {created}"
    )
    for s in expected:
        assert get_subject(s)["level"] == "L0_named"
    assert get_subject("mcx-services")["level"] == "L2_decomposed"

    res2 = build_scan_graph().invoke({"engagement": ENGAGEMENT, "db_path": str(DB_PATH)})
    held_after_mcx = len([g for g in res2.get("enriched_gaps", []) if g.get("held_premature") and g.get("subject") in ("mcx-services", "floor-control", "media-distribution", "lmr-interworking", "group-management")])
    released_mcx = held_before_mcx - held_after_mcx

    assert released_mcx >= 0, (
        f"a decomposition must release previously held questions for mcx-services "
        f"({held_before_mcx} → {held_after_mcx})"
    )

    dispatched_questions = res2.get("questions", [])

    report.note(f"""
        The decomposition created **{len(created)} sub-subjects** at `L0_named`
        (`group-management`, `floor-control`, `media-distribution`, `lmr-interworking`),
        engendered **{len(dispatched_questions)} active framing questions** dispatched to architects,
        advanced `mcx-services` to `L2_decomposed`, and released
        **{released_mcx}** previously held parameter gaps for `mcx-services`.
        Refinement is generative: it is the answer that creates what the next questions talk about.

        The base proposed **PAT-006**, written for a different domain, because
        the interworking part has the same shape: a vendor system that must be
        observed without being controlled. It reported having **no pattern** for
        the decomposition itself — a first occurrence, and a promotion candidate.
    """)
    report.mermaid("""
        graph TD
            MCX["mcx-services · L2_decomposed"]
            PAT["PAT-006 (candidate)<br/>when not to use: documented direct access"]
            PAT -. proposed .-> MCX
            MCX --> GM["group-management · L0"]
            MCX --> FC["floor-control · L0"]
            MCX --> MD["media-distribution · L0"]
            MCX --> LMR["lmr-interworking · L0"]
    """)
    report.board(repo, "Maturity board after decomposition")
    completed(state, "act-3")


# ============================================================== ACT 5a
def test_act5a_contest_declares_a_conflict(repo, report, state):
    """Contest is an explicit act, not an inference."""
    requires(state, "act-3")
    report.act("Act 5a — a declared conflict: an architect steps in")

    s34 = repo.get_active_statements(engagement=ENGAGEMENT)[0]["id"]
    s41, conflict_id = repo.contest_statement(
        target_statement_id=s34,
        author="Rui Vasconcelos",
        role="mobile-core-architect",
        text="depends on a committed priority and pre-emption profile in the core",
        engagement=ENGAGEMENT,
    )

    assert conflict_id is not None
    assert s41 is not None

    get_statement = api(repo, "get_statement", "the target must remain, but marked contested")
    a34 = get_statement(s34)
    a41 = get_statement(s41)
    assert a41["status"] == "active"

    get_conflict = api(repo, "get_conflict", "conflicts must be reified entities")
    conf = get_conflict(conflict_id)
    assert conf["status"] == "open"
    assert set(conf["statement_ids"]) == {s34, s41}

    report.note("""
        Rui contested statement `S-0003`. The target statement stays in the graph
        marked `contested`; a new counter-statement is created with confidence
        `assumed`; a `Conflict` entity is born connecting them. The machine does
        not resolve this — it holds both and waits for arbitration.
    """)
    report.table(["Statement", "Role", "Status", "Value"],
                 [[s34, "mcx-service-architect", a34["status"], a34["value"]],
                  [s41, "mobile-core-architect", a41["status"], a41["value"]]])
    state["conflict_declared"] = conflict_id
    state["s34"], state["s41"] = s34, s41
    completed(state, "act-5a")


# ============================================================== ACT 5b
def test_act5b_check_node_detects_a_conflict_nobody_declared(repo, report, state):
    """The path that actually proves detection: two statements, no contest."""
    requires(state, "act-3")
    report.act("Act 5b — a detected conflict: two answers collide without anyone noticing")

    common = {"engagement": ENGAGEMENT, "section": "4.4", "subject": "media-distribution",
              "predicate": "has_property", "confidence": "designed", "status": "active"}
    a = repo.save_statement({**common, "value": "multicast on the radio side",
                             "author": "Amina Duarte", "role": "mcx-service-architect"})
    b = repo.save_statement({**common, "value": "unicast only, multicast deferred",
                             "author": "Rui Vasconcelos", "role": "mobile-core-architect"})

    check = api(repo, "run_checks",
                "check_node must detect contradictions without a human declaring them")
    found = check(engagement=ENGAGEMENT, statement_ids=[b])

    detected = [c for c in found if c.get("kind") == "contradiction"]
    assert detected, (
        "two active statements on the same subject and predicate with different "
        "values must be detected. If only contest_statement can raise a conflict, "
        "the system declares disagreements but does not find them."
    )
    conf = detected[0]
    assert {a, b} <= set(conf["statement_ids"])
    assert conf.get("origin") == "detected"
    active = {s["id"] for s in repo.get_active_statements(engagement=ENGAGEMENT)}
    assert a in active and b in active, "detection must not withdraw either statement"

    stmt_a = repo.get_statement(a)
    stmt_b = repo.get_statement(b)

    report.note("""
        Neither architect contested anything: two answers on
        `media-distribution` landed independently and the check node found the
        contradiction by query. This is the path that proves detection works —
        a declared conflict proves only that a human can raise one.
    """)
    report.table(
        ["Statement Id", "Author", "Subject", "Value", "Conflict Id", "Origin"],
        [
            [a, stmt_a["author"], stmt_a["subject"], stmt_a["value"], conf["id"], conf.get("origin", "detected")],
            [b, stmt_b["author"], stmt_b["subject"], stmt_b["value"], conf["id"], conf.get("origin", "detected")],
        ]
    )
    state["conflict_detected"] = conf["id"]
    completed(state, "act-5b")


# ============================================================== ACT 6
def test_act6_arbitration_amends_keeps_and_generates(repo, report, state):
    """Arbitration is not winner-takes-all."""
    requires(state, "act-5a")
    report.act("Act 6 — arbitration: amend one, keep the other, record the consequence")

    s34, s41 = state["s34"], state["s41"]
    amended = "floor arbitration terminates in the MC service layer at the site"
    reason = ("Both are right and the disagreement is one of scope. Arbitration is "
              "local; the end-to-end floor grant is not, because it depends on "
              "admission in the core.")

    repo.arbitrate_conflict(
        conflict_id=state["conflict_declared"], keep_statement_id=s41,
        reason=reason, arbitrated_by="Sofia Lindqvist",
        amend_statement_id=s34, amend_to=amended,
    )

    get_statement = api(repo, "get_statement", "the amended statement must be inspectable")
    a34 = get_statement(s34)
    assert a34["value"] == amended and a34["status"] == "active"
    assert a34.get("previous_values"), (
        "the previous wording must survive: an amendment is a change, not an erasure"
    )
    assert get_statement(s41)["status"] == "active"

    get_conflict = api(repo, "get_conflict", "arbitration must be traceable")
    conf = get_conflict(state["conflict_declared"])
    assert conf["status"] == "arbitrated"
    assert reason[:40] in conf["resolution"], "the rationale is the deliverable"
    assert conf.get("arbitrated_by") == "Sofia Lindqvist"

    report.note("""
        Sofia amended one statement and kept the other, because the disagreement
        was one of scope rather than of substance. The previous wording is in the
        history. An arbitration that could only pick a winner would have forced
        her to discard a true statement.
    """)
    report.table(["Statement", "Status", "Value"],
                 [[s34, a34["status"], a34["value"]],
                  [s41, "active", get_statement(s41)["value"]]])
    completed(state, "act-6")


# ============================================================== ACT 7
def test_act7_assembly_is_provisional_for_a_maturity_reason(repo, report, state):
    """The discriminating test: provisional despite no open conflict."""
    requires(state, "act-6")
    report.act("Act 7 — assembly: provisional because subjects are immature")

    res = build_assemble_graph().invoke({"engagement": ENGAGEMENT, "db_path": str(DB_PATH)})

    assert res["is_provisional"] is True
    unripe = res.get("unripe_subjects", [])
    assert unripe, "a provisional document must name the subjects that are not ripe"

    open_conflicts = res.get("open_conflicts")
    assert open_conflicts is not None, (
        "assembly must report the number of open conflicts, otherwise a "
        "provisional status cannot be attributed to the right cause"
    )
    # The point of the whole act: arbitrating one conflict does not complete a document.
    assert res["is_provisional"] and open_conflicts <= 1, (
        "the document must remain provisional on maturity grounds even once "
        "conflicts are resolved"
    )

    sections = res.get("section_status", {})
    assert sections, "per-section status is required to know what is usable today"

    doc = ARTIFACTS / "document.md"
    doc.write_text(res.get("document", ""), encoding="utf-8")
    assert doc.stat().st_size > 0

    report.note(f"""
        Status **PROVISIONAL**, with **{open_conflicts}** conflict(s) open and
        **{len(unripe)}** subjects below `L3_decided`. The reason matters: the
        document is not held back by a disagreement but by immaturity. A run
        that reaches COMPLETE here has failed — this engagement is not finished.
    """)
    report.table(["Section", "Status"], [[k, v] for k, v in sorted(sections.items())])
    report.table(["Subject not ripe", "Level"],
                 [[u["subject"], u.get("level", "?")] for u in unripe])
    report.board(repo, "Maturity board at assembly")
    completed(state, "act-7")


# ============================================================== ACT 8
def test_act8_harvest_proposes_promotion_candidates(repo, report, state):
    """What makes any of this worth doing."""
    requires(state, "act-7")
    report.act("Act 8 — harvest")

    if build_harvest_graph is None:
        pytest.fail(
            "NOT IMPLEMENTED: flows/harvest.py is required. Without a harvest the "
            "base never learns from an engagement and is a filing cabinet."
        )

    res = build_harvest_graph().invoke(
        {"engagement": ENGAGEMENT, "db_path": str(DB_PATH), "by": "Sofia Lindqvist"})
    candidates = res.get("promotion_candidates", [])
    assert candidates, "the harvest must propose at least the decomposition"

    report.note("""
        The harvest proposes what generalises. Promotion requires a second
        occurrence on a different engagement, so nothing is promoted here — these
        are candidates, held until they recur.
    """)
    report.table(["Candidate", "Kind", "Rationale"],
                 [[c.get("title", "?"), c.get("kind", "?"),
                   c.get("why", "")] for c in candidates])
    (ARTIFACTS / "harvest.json").write_text(json.dumps(res, indent=2, default=str))
    completed(state, "act-8")
