"""``kb ingest-framework``: source -> draft controls in staging + framework manifest.

1. Acquisition: text extraction and SHA-256 of the source document.
2. Deterministic split into requirement units (``splitter.py``).
3. One **draft** control per unit in ``data/staging/<FW>/<version>/`` (ignored by git),
   in the format of the existing controls, with the legal text verbatim,
   ``status: draft`` and an empty ``validated_by``.
4. The manifest ``data/kb/controls/<FW>/_manifest.yaml`` records the version, the
   source SHA-256 and the expected requirements. A coverage declaration survives only
   if the version and the source are unchanged.
"""

from __future__ import annotations

import re
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

import yaml

from pipelines.frameworks.extract import compute_hash, extract_text
from pipelines.frameworks.splitter import Requirement, SplitterConfig, load_splitter, split
from pipelines.kb_candidates.kb import join_frontmatter
from pipelines.kb_candidates.owners import load_owners

INGESTION_FILE = "_ingestion.yaml"
MANIFEST_FILE = "_manifest.yaml"


def version_slug(version: str) -> str:
    return re.sub(r"[^A-Za-z0-9.]+", "-", version).strip("-") or "unversioned"


def staging_path(staging_dir: str | Path, framework: str, version: str) -> Path:
    return Path(staging_dir) / framework / version_slug(version)


def latest_staging(staging_dir: str | Path, framework: str) -> Path:
    """Most recently ingested version of a framework in staging."""
    base = Path(staging_dir) / framework
    runs = sorted((p for p in base.glob(f"*/{INGESTION_FILE}")), key=lambda p: p.stat().st_mtime)
    if not runs:
        raise FileNotFoundError(f"No ingestion of '{framework}' in {base}: run 'kb ingest-framework' first.")
    return runs[-1].parent


def manifest_path(kb_dir: str | Path, framework: str) -> Path:
    return Path(kb_dir) / "controls" / framework / MANIFEST_FILE


def load_manifest(kb_dir: str | Path, framework: str) -> dict[str, Any] | None:
    path = manifest_path(kb_dir, framework)
    if not path.is_file():
        return None
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data if isinstance(data, dict) else None


def write_manifest(kb_dir: str | Path, framework: str, manifest: dict[str, Any]) -> Path:
    path = manifest_path(kb_dir, framework)
    path.parent.mkdir(parents=True, exist_ok=True)
    if manifest.get("provisional"):
        origin = "PROVISIONAL (no source ingested yet): replace it by running `kb ingest-framework` on the source"
    else:
        origin = "Generated by `kb ingest-framework` from the source whose SHA-256 is recorded below"
    header = (
        f"# Coverage manifest of {framework} (plan L3 §6.1). {origin}.\n"
        "# `coverage_declared_by` is only set by the expert through `kb declare-coverage`.\n"
    )
    path.write_text(header + yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True, width=1000), encoding="utf-8")
    return path


def render_draft_control(
    unit: Requirement,
    cfg: SplitterConfig,
    version: str,
    source_sha256: str,
    owner: str,
    today: date,
) -> str:
    fm: dict[str, Any] = {
        "id": unit.id,
        "title": unit.title,
        "type": "control",
        "framework": cfg.framework,
        "version": version,
    }
    if cfg.jurisdiction:
        fm["jurisdiction"] = cfg.jurisdiction
    fm.update({
        "domain": list(cfg.defaults.get("domain") or []),
        "severity": cfg.defaults.get("severity", "mandatory"),
    })
    if cfg.defaults.get("target_entities"):
        fm["target_entities"] = list(cfg.defaults["target_entities"])
    fm.update({
        "status": "draft",
        "confidence": "assumed",
        "last_reviewed": today,
        "owner": owner,
        "source_ref": unit.ref,
        "source_sha256": source_sha256,
        "validated_by": [],
    })
    context = f"\n\n> Context: {unit.context}" if unit.context else ""
    body = (
        f"# {unit.id} — {unit.title}\n\n"
        f"## Regulatory Reference\n{unit.ref}.\n\n"
        f"## Legal Requirement\n{unit.text}{context}\n\n"
        "## Architecture Acceptance Criteria\n"
        "_To be proposed (`kb suggest-links`) and validated by the expert (`kb review-sheet`)._\n"
    )
    return join_frontmatter(fm, body)


def ingest_framework(
    framework: str,
    version: str,
    source: str | Path,
    kb_dir: str | Path = "data/kb",
    staging_dir: str | Path = "data/staging",
    splitter: str | Path | None = None,
    tag: str = "",
    today: date | None = None,
) -> dict[str, Any]:
    source = Path(source)
    if not source.is_file():
        raise FileNotFoundError(f"Source not found: {source}")
    cfg = load_splitter(framework, splitter)
    if "{tag}" in cfg.id_template and not tag:
        raise ValueError(f"The {framework} splitter needs --tag (e.g. the specification number).")
    sha = compute_hash(source)
    units = split(extract_text(source), cfg, tag=tag)
    if not units:
        raise ValueError(f"No requirement found in {source} with the {framework} splitter.")
    today = today or datetime.now(UTC).date()
    owner = load_owners(kb_dir).owner_for_domains(list(cfg.defaults.get("domain") or [])).handle.lstrip("@")

    out = staging_path(staging_dir, cfg.framework, version)
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("*.md"):
        stale.unlink()
    for unit in units:
        (out / f"{unit.id}.md").write_text(render_draft_control(unit, cfg, version, sha, owner, today), encoding="utf-8")
    ingestion = {
        "framework": cfg.framework,
        "version": version,
        "source": {"file": source.name, "sha256": sha},
        "ingested_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "splitter": str(splitter or f"pipelines/frameworks/splitters/{framework.lower()}.yaml"),
        "requirements": [u.id for u in units],
    }
    (out / INGESTION_FILE).write_text(yaml.safe_dump(ingestion, sort_keys=False, allow_unicode=True), encoding="utf-8")

    previous = load_manifest(kb_dir, cfg.framework) or {}
    unchanged = previous.get("version") == version and previous.get("source_sha256") == sha
    manifest = {
        "framework": cfg.framework,
        "version": version,
        "title": cfg.title,
        "source": {"file": source.name, "sha256": sha, "ingested_at": ingestion["ingested_at"]},
        "source_sha256": sha,
        "provisional": False,
        "expected_requirements": [u.id for u in units],
        "coverage_declared_by": previous.get("coverage_declared_by") if unchanged else None,
        "coverage_declared_at": previous.get("coverage_declared_at") if unchanged else None,
    }
    manifest_file = write_manifest(kb_dir, cfg.framework, manifest)
    return {
        "framework": cfg.framework,
        "version": version,
        "source_sha256": sha,
        "requirements": len(units),
        "staging_dir": str(out),
        "manifest": str(manifest_file),
        "declaration_reset": bool(previous.get("coverage_declared_by")) and not unchanged,
    }
