"""Generates docs/SCHEMA.md programmatically from Kùzu DB table catalogue (F9)."""

from pathlib import Path
import kuzu
from mcp_server.core.config import server_config


def generate_schema_markdown(knowledge_path: Path | str, engagement_path: Path | str) -> str:
    lines = [
        "# Kùzu DB Graph Schema Specification (ADR-015)",
        "",
        "This file is auto-generated by `pipelines/ingestion/generate_schema_doc.py` from active database catalogues.",
        "",
        "## 1. Knowledge Plane (`knowledge.kuzu`)",
        "",
    ]

    def _extract_schema(db_p: Path | str) -> list[str]:
        out = []
        if not Path(db_p).exists():
            out.append("*(Database not initialized)*\n")
            return out

        db = kuzu.Database(str(db_p))
        conn = kuzu.Connection(db)
        tables_res = conn.execute("CALL show_tables() RETURN name, type;")
        tables = []
        while tables_res.has_next():
            row = tables_res.get_next()
            if row:
                tables.append((str(row[0]), str(row[1])))

        tables.sort(key=lambda x: (x[1], x[0]))

        nodes = [t for t in tables if t[1].upper() in ("NODE", "NODE_TABLE")]
        rels = [t for t in tables if t[1].upper() in ("REL", "REL_TABLE", "RELATION")]

        out.append("### Node Tables")
        out.append("")
        for name, _ in nodes:
            out.append(f"#### `{name}`")
            try:
                cols_res = conn.execute(f"CALL table_info('{name}') RETURN name, type;")
                out.append("| Column | Type |")
                out.append("|---|---|")
                while cols_res.has_next():
                    c_row = cols_res.get_next()
                    if c_row:
                        out.append(f"| `{c_row[0]}` | `{c_row[1]}` |")
            except Exception:
                out.append("*(Table metadata unavailable)*")
            out.append("")

        out.append("### Relation Tables")
        out.append("")
        for name, _ in rels:
            out.append(f"#### `{name}`")
            try:
                cols_res = conn.execute(f"CALL table_info('{name}') RETURN *;")
                out.append("| Property / Connection | Details |")
                out.append("|---|---|")
                while cols_res.has_next():
                    c_row = cols_res.get_next()
                    if c_row:
                        out.append(f"| `{c_row[0]}` | `{c_row[1] if len(c_row) > 1 else ''}` |")
            except Exception:
                out.append("*(Relation metadata unavailable)*")
            out.append("")

        del conn
        del db
        return out

    lines.extend(_extract_schema(knowledge_path))
    lines.append("## 2. Engagement Plane (`engagements/<id>.kuzu`)")
    lines.append("")
    lines.extend(_extract_schema(engagement_path))

    return "\n".join(lines)


def update_schema_doc(out_path: Path | str = "docs/SCHEMA.md") -> str:
    kb_p = server_config.knowledge_db_path
    eng_p = server_config.engagements_dir / "nordwave-mcx-2027.kuzu"

    content = generate_schema_markdown(kb_p, eng_p)
    out_file = Path(out_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(content, encoding="utf-8")
    return str(out_file)


def main() -> None:
    path = update_schema_doc()
    print(f"✅ Schema documentation generated at {path}")


if __name__ == "__main__":
    main()
